#!/bin/sh

# Create wsn_setting directory for webmin module
cp -rf /home/adv/APIGateway/apps/wsn_manage/wsn_setting/* /home/adv/wsn_setting/
#only remove subdirectoy
mkdir -p /home/adv/wsn_setting/device_html
cd /home/adv/wsn_setting/device_html
rm -Rf -- */
#remove all files
mkdir -p /home/adv/wsn_setting/device_table
cd /home/adv/wsn_setting/device_table
rm -rf *

#Auto Run put it at /usr/local/bin
cd /home/adv/APIGateway
npm start
